### ISSUE TITLE
Private Daten oeffentlich

### ISSUE THREAD

**Issue by poggenpower** [momu/jvereintools#1]
Hallo,

ich weiss nicht ob es echte Daten sind, aber die example-export.cvs beinhaltet einige Datensaetze. Wenn dieses von echten Mitgliedern sind, sollten die nicht auf dieser Seite oeffentlich zur Verfuegung stehen.

Gruss
  Thomas

**Comment by momu** [comment]
Hallo Thomas,

nein keine Angst, sind nur Dummydaten.

Grüße
Moritz
